name: Build Editable
on:
  push:
      branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master  # リポジトリをチェックアウト

      - name: list_files  # ファイル一覧を表示
        run: find ./basic_js/ -type f -not -name ".*" | sort 

      - name: Join_files  # ファイルを結合
        run: find ./basic_js/ -type f -not -name ".*" | sort | xargs cat > ./deploy_files/basic2.js

      - name: install_babel  # babelをインストール
        run: npm install --save-dev @babel/core @babel/cli @babel/preset-env

      - name: preview  # 表示
        run: more ./deploy_files/basic2.js

      - name: babel  # コンパイル 
        run: npx babel ./deploy_files/basic2.js

      - name: Deploy_others  # S3にデプロイ 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws s3 cp --recursive --acl public-read --region ap-northeast-1 ./deploy_files s3://mono-editable